site_name: '{{ cookiecutter.project_name }}'

theme:
  name: 'material'

markdown_extensions:
  # Footnotes
  - footnotes
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Checkboxes
  - pymdownx.tasklist:
      custom_checkbox: true
  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  # Navigation page ordering
  - awesome-nav
  - search

nav:
  - Johdanto: johdanto.md
  - Projektiraportti:
    - Projektisuunnitelma: projektiraportti/01-projektisuunnitelma.md
    - Arkkitehtuuri: projektiraportti/02-arkkitehtuuri.md
    - Presentaatiokalvot: projektiraportti/xx-presentaatiokalvot.md
  - Päiväkirja: paivakirja.md
  - Viikkoraportit: weeks/
  - Yhteenveto: yhteenveto.md
  - Itsearviointi: self-evaluation.md

copyright: |
  {{ cookiecutter.author }} in {% now 'utc', '%Y' %}.